"""
akash-deploy: Python bindings for Akash Network proto types.

Includes both on-chain Akash types and Console API types.

Usage:
    from akash_deploy.console_deployment import ListDeploymentsRequest
    from akash_deploy.console_provider import ListProvidersRequest

Low-level encode/decode (requires native extension — run `just py-build`):
    from akash_deploy._native import encode_message, decode_message, registered_types
"""

# Re-export generated modules (populated by `just py-gen`)
try:
    from akash_deploy import (
        akash_audit_v1,
        akash_audit_v1beta3,
        akash_base_attributes_v1,
        akash_base_deposit_v1,
        akash_base_offchain_sign_v1,
        akash_base_resources_v1beta4,
        akash_base_v1beta3,
        akash_bme_v1,
        akash_cert_v1,
        akash_cert_v1beta3,
        akash_deployment_v1,
        akash_deployment_v1beta3,
        akash_deployment_v1beta4,
        akash_deployment_v1beta5,
        akash_discovery_v1,
        akash_downtimedetector_v1beta1,
        akash_epochs_v1beta1,
        akash_escrow_id_v1,
        akash_escrow_types_v1,
        akash_escrow_v1,
        akash_escrow_v1beta3,
        akash_inventory_v1,
        akash_manifest_v2beta3,
        akash_market_v1,
        akash_market_v1beta4,
        akash_market_v1beta5,
        akash_market_v2beta1,
        akash_oracle_v1,
        akash_provider_v1,
        akash_provider_v1beta3,
        akash_provider_v1beta4,
        akash_take_v1,
        akash_take_v1beta3,
        akash_wasm_v1,
        console_address,
        console_auth,
        console_bid,
        console_billing,
        console_block,
        console_certificate,
        console_dashboard,
        console_deployment,
        console_deployment_settings,
        console_gpu,
        console_lease,
        console_network,
        console_pricing,
        console_proposal,
        console_provider,
        console_provider_extended,
        console_stripe,
        console_template,
        console_transaction,
        console_user,
        console_validator,
    )
except ImportError:
    # Generated modules not yet present — run `just py-gen`
    pass

__all__ = [
    "akash_audit_v1",
    "akash_audit_v1beta3",
    "akash_base_attributes_v1",
    "akash_base_deposit_v1",
    "akash_base_offchain_sign_v1",
    "akash_base_resources_v1beta4",
    "akash_base_v1beta3",
    "akash_bme_v1",
    "akash_cert_v1",
    "akash_cert_v1beta3",
    "akash_deployment_v1",
    "akash_deployment_v1beta3",
    "akash_deployment_v1beta4",
    "akash_deployment_v1beta5",
    "akash_discovery_v1",
    "akash_downtimedetector_v1beta1",
    "akash_epochs_v1beta1",
    "akash_escrow_id_v1",
    "akash_escrow_types_v1",
    "akash_escrow_v1",
    "akash_escrow_v1beta3",
    "akash_inventory_v1",
    "akash_manifest_v2beta3",
    "akash_market_v1",
    "akash_market_v1beta4",
    "akash_market_v1beta5",
    "akash_market_v2beta1",
    "akash_oracle_v1",
    "akash_provider_v1",
    "akash_provider_v1beta3",
    "akash_provider_v1beta4",
    "akash_take_v1",
    "akash_take_v1beta3",
    "akash_wasm_v1",
    "console_address",
    "console_auth",
    "console_bid",
    "console_billing",
    "console_block",
    "console_certificate",
    "console_dashboard",
    "console_deployment",
    "console_deployment_settings",
    "console_gpu",
    "console_lease",
    "console_network",
    "console_pricing",
    "console_proposal",
    "console_provider",
    "console_provider_extended",
    "console_stripe",
    "console_template",
    "console_transaction",
    "console_user",
    "console_validator",
]

